### ISSUE TITLE
events.js:142 > Unhandled 'error' event

### ISSUE THREAD

**Issue by Shakalu** [Quramy/electron-connect#19]
Hi,

I'm novice in electron, node.js and gulp and i have trouble to understand this error :

```shell
npm install -g gulp
npm install electron-connect
gulp serve
```
Return me this :
```shell
[20:38:06] Starting 'serve'...
[20:38:06] Finished 'serve' after 2.99 ms
[2015-12-17T19:38:06.381Z] [electron-connect] [server] created and liseten to 30
080
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: spawn electron ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:179:32)
    at onErrorNT (internal/child_process.js:345:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
    at Function.Module.runMain (module.js:433:11)
    at startup (node.js:141:18)
    at node.js:977:3
```

gulfile.js
```javascript
'use strict';

var gulp = require('gulp');
var electron = require('electron-connect').server.create();

gulp.task('serve', function() {

  // Start browser process
  electron.start();

  // Restart browser process
  gulp.watch('main.js', electron.restart);

  // Reload renderer process
  gulp.watch(['index.html'], electron.reload);

});
```
main.js
```javascript
'use strict';

var app = require('app');
var BrowserWindow = require('browser-window');
var client = require('electron-connect').client;

var mainWindow;
var mainWindowState = { width: 1024, height: 800 };

app.on('ready', function () {

    mainWindow = new BrowserWindow({
        width: mainWindowState.width,
        height: mainWindowState.height
    });

    mainWindow.loadURL('file://' + __dirname + '/index.html');

    mainWindow.on('closed', function() {
        mainWindow = null;
    });

    // Connect to server process
    client.create(mainWindow);

});
```

index.html
```html
...
...
...
        <!-- build:remove -->
        <!-- Connect to server process -->
        <script>require('electron-connect').client.create()</script>
        <!-- end:build -->
</body>
</html>
```

Thanks for your help. :)

**Comment by darkyen** [comment]
^ same

**Comment by gabepaez** [comment]
+1

**Comment by gabepaez** [comment]
@Shakalu & @darkyen: I just figured this out. The module requires that you have electron-prebuilt installed either locally or globally. The Readme should be more specific on this point but it hints to it here:

```
If neither electron nor useGlobalElectron are set, electron-connect searches electron-prebuilt modules automatically.

1. First, electron-connect searches electron-prebuilt installed locally.
2. If not hit, electron-connect uses electron-prebuilt installed globally.
```

if you run `npm install electron-prebuilt` then your `gulp serve` should start to work.

**Comment by darkyen** [comment]
Yeah I figured that out too, electron was started globally for me. :-( and the option didn't help.

**Comment by ssreekanth** [comment]
Can not reproduce it. Closing this out.

**Comment by alex1012** [comment]
+1

**Comment by alex1012** [comment]
my error log

`[2016-10-08T21:16:28.134Z] [electron-connect] [server] started electron process: undefined
[2016-10-08T21:16:28.134Z] [electron-connect] [server] created and listening on 30080
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn electron ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3
`

**Comment by ssreekanth** [comment]
@alex1012 Is `electron` npm module installed locally or globally in your setup?

**Comment by alex1012** [comment]
@ssreekanth i have resolved this problem, thanks. But, way to that solution surprised me.

For solution i was necessary to install `electron `and `electron-prebuilt` npm modules, both. I'm novice in electron, but what i know `electron` is a heir for `electron-prebuilt` and exactly this surprised me.

**Comment by alex1012** [comment]
@ssreekanth if this important for you i can research this problem in my case.

**Comment by ssreekanth** [comment]
That's great. `electron-prebuilt` npm module will be deprecated by end of this year. `electron` npm module is the replacement for that.

**Comment by ssreekanth** [comment]
That's great. `electron-prebuilt` npm module will be deprecated by end of this year and is replaced by `electron` npm module. At this time, any one of them will work.
