### ISSUE TITLE
stopping the process on window close

### ISSUE THREAD

**Issue by rootsical** [Quramy/electron-connect#2]
thank you for this great project. i was just wondering if it is possible to stop the process on closing the app window by using an event handler or similar? thanks

**Comment by rootsical** [comment]
what i meant was the gulp was still carrying on after the electron window was closed. i have sorted this by doing the following in the main electron js file:
```javascript 
var client = electronConnect.client.create(mainWindow);
```
where 
```javascript
var electronConnect = require('electron-connect');
```    
the client can emit a message on the window being closed:
```javascript
mainWindow.on('closed', function() {
	mainWindow = null;
	client.sendMessage('closed');
});
```
in the gulpfile.js, you can then add:
```javascript
electron.on('closed', function(){
	process.exit();
});
```

**Comment by mchristofersen** [comment]
Thanks for this, I love this project but the processes stay open was driving me nuts.

**Comment by ssreekanth** [comment]
@mchristofersen you should use `stopOnClose` option. Here is the snippet from the documentation -

---

**New in version 0.5.x and onwards :**
Now, ProcessManager's `start()`, `restart()` and `stop()` methods invoke ``callback`` with an argument that indicates the `state` of the electron process, which could be one of the following string values -
* `started`
* `restarting`
* `restarted`
* `stopped`

See [example/stop-on-close](example/stop-on-close), where you can find sample code that uses `stopOnClose` option and `stopped` state to shutdown gulp process gracefully.

---
