### ISSUE TITLE
Shouldn't spawn args be prepended and not appended?

### ISSUE THREAD

**Issue by nickgzzjr** [Quramy/electron-connect#20]
I tried to require a node package using the `-r` argument for electron but it wasn't working. I realized the args were being appended to the spawn after the path but these arguments should be prepended.

Original
`this.electronProc = proc.spawn(this.opt.electron, [this.opt.path].concat(args), spawnOpt);`

Fix
`this.electronProc = proc.spawn(this.opt.electron, args.concat([this.opt.path]), spawnOpt);`

If this works for everyone then I can create a pull request with my fix.

**Comment by ssreekanth** [comment]
@nickgzzjr please create a pull request with your fix.

**Comment by ssreekanth** [comment]
Fixed. Closing this out.
