### ISSUE TITLE
electron.reload doesn't work

### ISSUE THREAD

**Issue by MarioHofer** [Quramy/electron-connect#28]
The following code inside my gulpfile.js works when using electron.restart, but does nothing when using electron.reload.

```javascript
var
	gulp = require('gulp'),
	electron = require('electron-connect').server.create()
;

gulp.task('serve', function () {
	electron.start();
	gulp.watch(['app/**/*'], electron.reload);
});
```

Is this a bug or am I missing something?

_(There was a new Electron release two days ago. Just in case...)_

**Comment by chrisbraddock** [comment]
+1

**Comment by ricardomatias** [comment]
+1

**Comment by Quramy** [comment]
I installed the latest electron-prebuilt(0.36.10) but I can't reproduce this issue.

Do you write the following in your index.html ?

```html
<html>
<body>

<!-- your app -->

<script>require('electron-connect').client.create()</script>
</body>
</html>
```

**Comment by MarioHofer** [comment]
RTFM, @MarioHofer!

Thanks, @Quramy. That solved the issue.
