### ISSUE TITLE
Don't include electron-prebuilt as a dependency

### ISSUE THREAD

**Issue by dylang** [Quramy/electron-connect#3]
Because `electron-prebuilt` is a dependency, we are locked to the version hardcoded in `electron-connect`'s `package.json`, which is currently out-of-date.

If you include it as a `peer-dependency` (and maybe `dev-dependency` for development, I'm not sure), it means developers including `electron-connect` in their `package.json` are responsible for *also* including `electron-prebuilt`, and this gives developers the flexibility of what version to include.

**Comment by Quramy** [comment]
Hi @dylang .

You can use `electron` option to control electron-prebuilt version.

```js
var server = require('electron-connect').server.create({
  electron: require('electron-prebuilt')
});

server.start();
```

**Comment by SamyPesse** [comment]
@dylang :+1: `electron-rebuilt` is a also a very big dependency

**Comment by Quramy** [comment]
I removed dependency of `electron-prebuilt` at v0.3.0 .

By the default, electron-connect searches and uses installed `electron-prebuilt`.

**Comment by ssreekanth** [comment]
Closing this issue.
