### ISSUE TITLE
Need better test scripts to verify commits.

### ISSUE THREAD

**Issue by ssreekanth** [Quramy/electron-connect#37]
Current test script doesn't verify whether electron app was created successfully or not. Test gets passed even when there is an issue with starting electron app from **simple** example code.

**Comment by ssreekanth** [comment]
@Quramy I'm currently looking into #32 issue. I'm pretty close to finishing it. While i'm working on it, i can handle this one too.

My proposal is to introduce arguments in the callback functions passed to start(), restart() and reload() which will tell about the state of the electron process (started, restarted, stopped etc.), pid and any error code.

**Comment by Quramy** [comment]
I think it's a nice idea! If you do not mind, please send PR or sample code of test scripts.

**Comment by Quramy** [comment]
Thanks for your quick PR!

**Comment by ssreekanth** [comment]
For now, **spectron** serves the purpose. We can add more tests if needed.

So, my proposal above applies to #32 though.
