### ISSUE TITLE
Electron 1.1 not working

### ISSUE THREAD

**Issue by b0c1** [Quramy/electron-connect#41]
Hi!

I try to use electron-connect with eletron 1.1.1.
My code:
```
'use strict';

import app from 'app'
import BrowserWindow from 'browser-window'
import {client} from 'electron-connect'

app.on('window-all-closed', () => {
    if (process.platform != 'darwin') {
        app.quit();
    }
});

app.on('ready', () => {
    var mainWindow = new BrowserWindow({width: 500, height: 300});
    mainWindow.webContents.openDevTools();
    mainWindow.loadURL(`file://${__dirname}/client/app.html`);
    client.create(mainWindow);
});
```

But the window is not created. When I start from console (electron app.js) or create electron application it's open the window.

Any idea?

**Comment by ssreekanth** [comment]
@b0c1 Works for me! can you paste your _gulpfile.js_?

**Comment by nripendra** [comment]
I believe it is due to api change:

import {app} from 'electron'
import {BrowserWindow} from 'electron'

**Comment by ssreekanth** [comment]
@bc01 closing this out, as it works well with electron 1.1.x as mentioned in my previous comment.
