### ISSUE TITLE
Unable to get logging working

### ISSUE THREAD

**Issue by zlepper** [Quramy/electron-connect#42]
I'm unable to get logging from electron working when i'm running electron via electron-connect. 
My gulpfile.js, index.html and main electron.ts file can be seen here https://gist.github.com/zlepper/3b5f31bd2bdb707f0311a350f3b9ec34

I'm passing along "--enable-logging" to both electron.start and electron.restart, and yet nothing appears in the console when logging is supposed to happen.

**Comment by ssreekanth** [comment]
@zlepper, In your  ``gulpfile.js``, try replacing
```js
var t6 = gulp.watch('app/**/*', [electron.restart("--enable-logging")]);
```
with
```js
var t6 = gulp.watch('app/**/*', function() {
     electron.restart("--enable-logging")
});
```

**Comment by ssreekanth** [comment]
@zlepper closing this out, as it is not an issue with electron-connect.
