### ISSUE TITLE
Set environment vars

### ISSUE THREAD

**Issue by garrettheel** [Quramy/electron-connect#5]
It would be great to be able to set environment variables when running the app, such as `NODE_ENV`.

This could be in the options of `start`.

**Comment by officert** [comment]
Same here, would be awesome to be able to set NODE_ENV

**Comment by inukshuk** [comment]
You can do that already, if I am not mistaken. First off, you can simply set any environment variable before starting the server (as they would be inherited), but you can also pass `spawnOpt` to `create`.

**Comment by ssreekanth** [comment]
@garrettheel closing this issue, as @inukshuk mentioned, you can do it by passing ENV variables in ``spawnOpt`` to ``create()``
