### ISSUE TITLE
yargs fails with latest update

### ISSUE THREAD

**Issue by JeroenVinke** [Quramy/electron-connect#54]
Hello, thanks for working on this great library :+1: 

Over the last few days we noticed that `yargs` did not work correctly anymore. Somehow the `--env="production"` variable that we pass to electron-connect's start function did not properly set the environment variable anymore.

I was able to reproduce it [here](https://github.com/JeroenVinke/electron-connect-args), where it works fine with v0.4.5 but it fails with v0.4.7.

**Comment by ssreekanth** [comment]
@JeroenVinke Thank you for reporting the issue. Fix is available in v0.4.8. Let us know if you see any other issues.

Closing this out.

**Comment by JeroenVinke** [comment]
Excellent, thanks for the quick turnaround. I was able to confirm that it works in v0.4.8 again
