### ISSUE TITLE
Doesn't work with Electron 0.31.0

### ISSUE THREAD

**Issue by damnhandy** [Quramy/electron-connect#6]
I was starting new project and used the latest version of Electron (0.31.0) and no content was visible nor were there any errors in the console or the browser view. Just a blank app, but the title is visible. . I'm basically starting with the simple example in the repository. Rolling back to 0.30.5 fixes the problem.

**Comment by Quramy** [comment]
Hi @damnhandy .

I tried with `electron-prebuilt@0.31.0` but I cannot reproduce your issue...

**Comment by Quramy** [comment]
I reproduced your issue.

And I think the reason is that `electron-prebuilt@~0.31.0` crashes when `require('ws')`. (electron-connect depends on `ws` module).

I'll investigate more to fix this issue.

**Comment by Quramy** [comment]
Hi @damnhandy .

What's version your node.js(or iojs) ?

Please try the following:

```bash
nvm use iojs-v3.1.0
rm -rf node_modules/electron-connect
npm install
gulp serve
```

electron-connect uses `ws` module. And `ws` uses `node-gyp` for it's dependencies.
And electron v0.31.0 includes iojs-v3.1.0. So if your node.js's version isn't this, your `ws` may use invalid binary for electron.

**Comment by ssreekanth** [comment]
I'm experiencing the same issue with electron 0.31.2. I guess you should provide a way to rebuild electron-connect and its' dependencies, at the time of npm install, using electron headers, so that native modules gets built correctly.

**Comment by damnhandy** [comment]
I'm using Node v0.12.7. I'll give io.js a try later on in the week.

**Comment by damnhandy** [comment]
@ssreekanth having electron-connect rebuild electron for node.js seem way out of scope for the projects intended goal. The fact that Electron bundles iojs, it makes sense that it might not work under nodejs.

**Comment by donnguyen** [comment]
@Quramy I'm experiencing the same issue with Electron v0.32.3 and Node v4.0.0. Do we have any plan to make this awesome works again with the latest version of Electron and Node? Thanks!
