### ISSUE TITLE
Not allowed to load local resource: data:text/html,chromewebdata:1

### ISSUE THREAD

**Issue by bertofer** [Quramy/electron-connect#60]
My application launches fine, but when I am watching some file, and invoke 'reload' this error happends, leaving a white screen with no app loaded:

```
Not allowed to load local resource: file:///Users/alberto/Projects/personal/angular2-electron/dist/
```

**Comment by ssreekanth** [comment]
@bertofer can you please post sample [gist](https://gist.github.com) to reproduce the issue?

**Comment by bertofer** [comment]
Hi! We finally solved it, here's the issue with the solution we did:

- https://github.com/bertofer/angular2-electron/issues/3
