### ISSUE TITLE
Why start is so slow?

### ISSUE THREAD

**Issue by kcampion** [Quramy/electron-connect#61]
When I start electron-connect with gulp, it take about 30 sec to launch the app:
```
[13:25:51] Using gulpfile ~/Documents/Projects/myproject/gulpfile.js
[13:25:51] Starting 'start'...
[13:26:17] Finished 'start' after 26 s
```

I'm under MacOs Sierra, node v6.7.0, gulp v3.9.1, gulp CLI v1.2.1 and electron-connect v0.6.0

**Comment by ssreekanth** [comment]
@kcampion We have never had any such issue with `electron-connect`. Can you identify if your app itself is taking so long to start up?

**Comment by kcampion** [comment]
@ssreekanth My app starts in less than 1 sec with `# electron .`
I continue the investigations to know why.

**Comment by kcampion** [comment]
@ssreekanth My apologies, I forgot to exclude the Bower folder into the gulp watch:

`gulp.watch(['index.html', 'app/**/*.js', '!app/bower_components/**', 'app/assets/css/**/*.css'], electron.reload);`

Now, the starting of electron-connect takes 3 sec :)

**Comment by ssreekanth** [comment]
@kcampion 👍
