### ISSUE TITLE
Actual JS logging

### ISSUE THREAD

**Issue by taboca** [Quramy/electron-connect#63]
I wonder if it makes sense the content's JS logging to also be an option as part of electron-connect. Say you have an option to log JS window content, such as contentLogging:true

**Comment by ssreekanth** [comment]
You can use electron's `--enable-logging` command line argument. Refer #42 issue and [gist](https://gist.github.com/ssreekanth/78d589034a88447c0f1e5efff57a88db) for more details.

Closing this issue out.
